CREATE DATABASE AULA4_EX
GO
USE AULA4_EX

CREATE TABLE CLIENTE (
ID INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR (50) NOT NULL,
CPF VARCHAR (15) UNIQUE NOT NULL ,
ENDERECO VARCHAR (50) NOT NULL,
TELEFONE VARCHAR (11) NOT NULL
)
GO
CREATE TABLE ITENS (
ID INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR (20) NOT NULL,
DESCRICAO VARCHAR (50),
VALOR SMALLMONEY NOT NULL
)
GO
CREATE TABLE VENDAS(
DATA_VENDA DATE NOT NULL,
ID  INT PRIMARY KEY IDENTITY (1,1),
ID_CLIENTE INT REFERENCES CLIENTE (ID)
)
GO
ALTER TABLE CLIENTE DROP COLUMN TELEFONE, ENDERECO
GO
CREATE TABLE ENDERECO (
ID INT IDENTITY (1,1) PRIMARY KEY,
ID_CLIENTE INT REFERENCES CLIENTE (ID) ,
RUA VARCHAR (50) NOT NULL,
BAIRRO VARCHAR (30) NOT NULL,
NUMERO INT NOT NULL
)
GO
CREATE TABLE  TELEFONE (
ID INT IDENTITY (1,1) PRIMARY KEY,
ID_CLIENTE INT REFERENCES CLIENTE (ID) ,
 NUMERO VARCHAR (12)
)
GO
CREATE TABLE VENDAS_X_ITENS (
ID_ITEM INT REFERENCES ITENS (ID),
ID_VENDA INT REFERENCES VENDAS (ID)
)
GO 
INSERT INTO CLIENTE (NOME, CPF) VALUES ('Maria', '09432569856') , ('Aline','02154689568'),('João','01457896587')

DECLARE @ID_CLIENTE INT 

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '02154689568'
INSERT INTO TELEFONE(ID_CLIENTE, NUMERO) VALUES (@ID_CLIENTE, '48985003513')

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '09432569856'
INSERT INTO TELEFONE(ID_CLIENTE, NUMERO) VALUES (@ID_CLIENTE, '048998546878')

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '01457896587'
INSERT INTO TELEFONE(ID_CLIENTE, NUMERO) VALUES (@ID_CLIENTE, '48998541236')

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '01457896587'
INSERT INTO ENDERECO(ID_CLIENTE, RUA, BAIRRO, NUMERO) VALUES (@ID_CLIENTE, 'Rua Girassol', 'Lagoa', 10)

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '09432569856'
INSERT INTO ENDERECO(ID_CLIENTE, RUA, BAIRRO, NUMERO) VALUES (@ID_CLIENTE, 'Rua Goiaba', 'Centro', 105)

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '02154689568'
INSERT INTO ENDERECO(ID_CLIENTE, RUA, BAIRRO, NUMERO) VALUES (@ID_CLIENTE, 'Rua Tiradentes', 'Coqueiros', 250)

INSERT INTO ITENS (NOME, DESCRICAO, VALOR) VALUES ('Coca-Cola', 'Refrigerante', 8.99), ('Pizza Sadia Calabresa',
												'Pizza Sadia sabor Calabresa', 14.99), ('Melância', 'Fruta', 1.99)



SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '02154689568'
INSERT INTO VENDAS (DATA_VENDA, ID_CLIENTE)VALUES ('2023-03-17',@ID_CLIENTE)

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '09432569856'
INSERT INTO VENDAS (DATA_VENDA, ID_CLIENTE)VALUES ('2023-03-17',@ID_CLIENTE)

SELECT @ID_CLIENTE = ID FROM CLIENTE WHERE CPF = '01457896587'
INSERT INTO VENDAS (DATA_VENDA, ID_CLIENTE)VALUES ('2023-03-17',@ID_CLIENTE)



DECLARE @ID_VENDA INT, @ID_ITEM INT 
SELECT @ID_VENDA = VENDAS.ID FROM VENDAS JOIN CLIENTE C ON C.ID = VENDAS.ID_CLIENTE WHERE C.CPF = '02154689568' 
SELECT @ID_ITEM = ID FROM ITENS WHERE NOME = 'Coca-Cola'
INSERT INTO VENDAS_X_ITENS (ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)
SELECT @ID_ITEM = ID FROM ITENS WHERE NOME = 'Melância'
INSERT INTO VENDAS_X_ITENS (ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)

SELECT @ID_VENDA = VENDAS.ID FROM VENDAS JOIN CLIENTE C ON C.ID = VENDAS.ID_CLIENTE WHERE C.CPF = '09432569856' 
SELECT @ID_ITEM = ID FROM ITENS WHERE NOME = 'Pizza Sadia Calabresa'
INSERT INTO VENDAS_X_ITENS (ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)
SELECT @ID_ITEM = ID FROM ITENS WHERE NOME = 'Melância'
INSERT INTO VENDAS_X_ITENS (ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)

SELECT @ID_VENDA = VENDAS.ID FROM VENDAS JOIN CLIENTE C ON C.ID = VENDAS.ID_CLIENTE WHERE C.CPF = '01457896587' 
SELECT @ID_ITEM = ID FROM ITENS WHERE NOME = 'Pizza Sadia Calabresa'
INSERT INTO VENDAS_X_ITENS (ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)
SELECT @ID_ITEM = ID FROM ITENS WHERE NOME = 'Coca-Cola'
INSERT INTO VENDAS_X_ITENS (ID_VENDA, ID_ITEM) VALUES (@ID_VENDA, @ID_ITEM)


SELECT FROM 